In [1]:
#1) Write a program to create a 5 dimensional array with all zeros and ones


In [34]:
import numpy as np
a=np.zeros((5,5))

In [41]:
np.array(a,ndmin=5,dtype=int)

array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]])

In [42]:
b=np.ones((5,5))

In [43]:
np.array(b,ndmin=5,dtype=int)

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

In [36]:
#2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create 
#a new array of shape (3,10)

In [49]:
zeros= np.zeros(10, )
ones= np.ones(10, )
fives= np.full(10,5)
array=np.array((zeros,ones,fives),dtype=int)

In [50]:
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [51]:
#3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [58]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
#4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [65]:
np.diag(np.arange(0,10))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [66]:
#5 Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [103]:
a=np.arange(1,17).reshape(4,4)

In [104]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [105]:
a[:,[0,-1]]=a[:,[-1,0]]
a[:,[1,2]]=a[:,[2,1]]


In [106]:
a

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [107]:
#6) Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [110]:
array=np.arange(12,28)

In [115]:
array[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [ ]:
#7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 
#from an array of shape 10,10 .Elements range from 1 to 100

In [119]:
c=np.arange(1,101).reshape(10,10)

In [120]:
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [124]:
c1=c[(c>30)&(c<80)&(c%5==0)]

In [125]:
c1

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [126]:
#8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [156]:
array=np.ones((5,5),dtype=int)


In [157]:
array[1:-1,1:-1]=0

In [158]:
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [159]:
#9) Write a program to create a checkerboard pattern .Don't use default array function
                                                 


In [162]:
array=np.ones((8,8),dtype=int)

In [164]:
array[1::2,::2]=0
array[::2,1::2]=0

In [165]:
array

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [166]:
# 10) Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]


In [167]:
a=np.array([1,1,1,12,2,3,4,5,5,67,78,6,54,3,3,2,56,7,7,7,8,8,65,5,4,4,4,3,4,6,7,6])
b=np.array([1,31,22,2,3,65,432,1233,453,6785,67875,7654,10,12,20,30,33311,234,])

In [172]:
x=np.intersect1d(a,b)

In [173]:
x

array([ 1,  2,  3, 12, 65])

In [174]:
# 11)Write a program to create an array 2d array and then reshape into 1d array

In [176]:
array=np.arange(1,11).reshape(5,2)

In [179]:
array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [181]:
array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
#12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [200]:
def ndarray(a):
    n=int(input("enter the dimension: "))
    if type(a)==list or type(a)==tuple:
        c=len(a)
    if n==1:
        print("array({})".format(a))
    elif(n==0):
        m=int(l[0])
        print("array({})".format(m)) 
    elif (n==2):    
       
        if(len(a[0])>1):
            print("array([",end="")
            for i in range(c):
                print("[{}]".format(a[i]))
            print("])")
        else:
            new=[]
            for i in a:
                if (i.isdigit()):
                    z=int(i)
                    new.append(z)
            print("array([{}])".format(new)) 
    else:
        pass
l=[]
n=int(input("enter the range: "))
for i in range(n):
    num=input("enter the elements: ")
    l.append(num)
print(l)
ndarray(l)
            

enter the range: 4
enter the elements: 1,2,3,4
enter the elements: 2,3,4,5
enter the elements: 3,4,5,6
enter the elements: 1,2,3,4
['1,2,3,4', '2,3,4,5', '3,4,5,6', '1,2,3,4']
enter the dimension: 2
array([[1,2,3,4]
[2,3,4,5]
[3,4,5,6]
[1,2,3,4]
])
